service: test-service
package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  js:
    handler: app.handler
    package:
      exclude:
        - vendor/**
        - php-src/**
        - "*.php"
        - composer.json
        - composer.lock

  php:
    handler: fn-generate.handler
    runtime: provided
    layers:
      - arn:aws:lambda:us-east-1:887080169480:layer:php71:9
      - {Ref: VendorLambdaLayer}
      - {Ref: RuntimeLambdaLayer}
    package:
      exclude:
        - node_modules/**
        - "*.js"
        - package.json
        - package-lock.json

layers:
  runtime:
    path: layer/php
  vendor:
    path: vendor